name: benjamin_web
description: "A new Flutter project for landing page." 
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.4 
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  card_swiper: ^3.0.1
  flutter_svg: ^2.0.14
  http: ^1.2.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
